#!/usr/bin/env python3
"""Mirror graph.jsonld into a served <script type="application/ld+json"> block in
traffic/dashboard/index.html.

graph.jsonld is a raw repo file, not structured data embedded in a served page.
Crawlers that read JSON-LD from HTML <head>/<body> markup never see it unless it
is mirrored into a page GitHub actually serves. traffic/dashboard/index.html is
that page (already indexable, already carries Dataset JSON-LD for the traffic
and probe datasets); this script keeps a full copy of graph.jsonld in sync there.

Run after any graph.jsonld edit, before committing.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GRAPH = ROOT / "graph.jsonld"
DASHBOARD = ROOT / "traffic" / "dashboard" / "index.html"

BEGIN = "<!-- BEGIN graph-jsonld-mirror (auto-generated by scripts/sync_graph_jsonld_mirror.py — do not hand-edit; edit graph.jsonld and re-run instead) -->"
END = "<!-- END graph-jsonld-mirror -->"


def main() -> None:
    graph_content = GRAPH.read_text(encoding="utf-8").rstrip("\n")
    html = DASHBOARD.read_text(encoding="utf-8")
    block = (
        f"{BEGIN}\n"
        '  <script type="application/ld+json" id="research-program-graph-mirror">\n'
        f"{graph_content}\n"
        "  </script>\n"
        f"  {END}"
    )
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
    if pattern.search(html):
        new_html = pattern.sub(block, html)
    else:
        marker = "  </script>\n"
        idx = html.index(marker) + len(marker)
        new_html = html[:idx] + "  " + block + "\n" + html[idx:]
    if new_html != html:
        DASHBOARD.write_text(new_html, encoding="utf-8")
        print(f"updated {DASHBOARD}")
    else:
        print("no change")


if __name__ == "__main__":
    main()
