#!/usr/bin/env python3
"""Mirror vocab.jsonld into the <script type="application/ld+json"> block in vocab.html.

vocab.jsonld is the canonical machine-readable vocabulary (RDFS + schema.org
domainIncludes/rangeIncludes). GitHub Pages cannot content-negotiate, so the same
definitions are served two ways: the raw vocab.jsonld file for direct fetch, and an
inline copy in vocab.html <head> for crawlers that only read JSON-LD embedded in
served HTML. This script keeps the inline copy in sync.

Run after any vocab.jsonld edit, before committing.
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VOCAB_JSONLD = ROOT / "vocab.jsonld"
VOCAB_HTML = ROOT / "vocab.html"

BEGIN = "<!-- BEGIN vocab-jsonld-mirror (auto-generated by scripts/sync_vocab_jsonld_mirror.py — do not hand-edit; edit vocab.jsonld and re-run instead) -->"
END = "<!-- END vocab-jsonld-mirror -->"


def main() -> None:
    jsonld_content = VOCAB_JSONLD.read_text(encoding="utf-8").rstrip("\n")
    json.loads(jsonld_content)  # refuse to mirror a malformed vocab.jsonld
    html = VOCAB_HTML.read_text(encoding="utf-8")
    block = (
        f"{BEGIN}\n"
        '<script type="application/ld+json" id="vocab-jsonld-mirror">\n'
        f"{jsonld_content}\n"
        "</script>\n"
        f"{END}"
    )
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
    if not pattern.search(html):
        raise SystemExit(
            f"marker block not found in {VOCAB_HTML}; add {BEGIN} … {END} to <head>"
        )
    new_html = pattern.sub(lambda _: block, html)
    if new_html != html:
        VOCAB_HTML.write_text(new_html, encoding="utf-8")
        print(f"updated {VOCAB_HTML}")
    else:
        print("no change")


if __name__ == "__main__":
    main()
